### PR TITLE
Adding level 100 MCH work

### PR DESCRIPTION
**Pull request by kbrighton**
This is what I've been using recently,  so it should (at least) be a good starting point.

### CODE REVIEW

**Comment by PrincessRTFM** [comment]
All of your changes are unconditional, meaning the user cannot turn them on or off. This is not how the plugin operates, so we can't accept this as it currently stands.

We're both working on getting XCVX updated for patch 7.0, and at present, there are only seven jobs left to be looked over. Minimal functionality should be available soon, and we will be looking at your changes when addressing MCH, assuming you don't add the necessary presets before then. If you do, you're welcome to update this, and we may be able to just accept your work directly in that case.

I'm leaving this PR open in case you want to do that, although I might recommend making a new branch on your repo that _only_ contains the MCH fixes and PRing _that_, instead of a bunch of unrelated commits that you then try to just undo.

**Comment by kbrighton** [comment]
Yeah, that's fair.  I was just working on getting minimal stuff working for myself and figured I'd send out a PR with that in there so there could  be a  baseline if it were useful.  If I get some time I'll see about making that all configurable, but if you get to it before I make that work, feel free to use whatever I've done so far as a base.

**Comment by kbrighton** [comment]
So, I added toggles for the new abilities.  I didn't do it for  heat blast->Blazing shot, because it seemed to just be an update, but I can add that in, if you'd like.

**Comment by PrincessRTFM** [comment]
I actually just finished updating MCH, although I used some of your work as a base to figure out a few things, and I may incorporate more. Frankly, I just _really_ wanted to finally start playing. If you've done anything with Excavator or Full Metal Field, those might be useful, but right now I'm about to get in game for the first time in a couple months.

**Comment by kbrighton** [comment]
Please do!  It's one of the reasons that I tried to get this PR out to  you, since it would take some load out.  I did do Excavator, but didn't really do anything with Full Metal Field yet, save for defining the buff and the action ID.  Likely what I'd do is add in an option to change Barrel Stabilizer to Full Metal Field if the buff is active.

**Comment by PrincessRTFM** [comment]
I've finally had a chance to look over your changes properly, and I think I've incorporated everything appropriate. A few notes:

- When game actions normally upgrade from traits, never use the old action (always use `OriginalHook()`) because without third-party client modifications, it's not _possible_ to use the old action anymore. That's a _dead_ giveaway that you're doing something against TOS.
- Your preset to become Excavator is in the wrong place and has the wrong description - and is also unnecessary. Chain Saw is `OriginalHook()`'d in the cooldown selection call, so it'll be replaced with Excavator normally as it is.

**Comment by kbrighton** [comment]
Cool.  At the very  least I hope it was helpful!  It was my first time really working on one of the plugins, and a good learning experience for  me.

**Comment by PrincessRTFM** [comment]
It was, and if it helped you learn, then it wouldn't have been a waste even if I used nothing!

**Comment by kbrighton** [comment]
Exactly.  I've learned in my years that you can often learn more by messing up than getting it perfect the first time around!  Have a good one.

**Pull request closed without merging**
